# Generated by Django 2.2.3 on 2019-08-08 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='party',
            fields=[
                ('party_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('finish_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_list', models.TextField()),
                ('poi_id', models.IntegerField(default=0)),
                ('pro_num', models.IntegerField(default=0)),
                ('con_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_id', models.IntegerField(default=0)),
                ('addr', models.TextField()),
                ('img_list', models.TextField()),
                ('ugc', models.TextField()),
                ('poi_type', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('special', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('headurl', models.TextField()),
                ('level', models.IntegerField(default=0)),
                ('point', models.FloatField()),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('hobby', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='user_party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.IntegerField(default=0)),
                ('party_id', models.IntegerField(default=0)),
            ],
        ),
    ]
